# update.packages(ask = FALSE)

try(require("shiny")||install.packages("shiny"))
try(require("tidyr")||install.packages("tidyr"))
try(require("dplyr")||install.packages("dplyr"))
try(require("ggplot2")||install.packages("ggplot2"))
try(require("DT")||install.packages("DT"))
try(require("reshape2")||install.packages("reshape2"))
try(require("wordcloud")||install.packages("wordcloud"))
try(require("plotly")||install.packages("plotly"))
try(require("udpipe")||install.packages("udpipe"))
try(require("textrank")||install.packages("textrank"))
try(require("lattice")||install.packages("lattice"))
try(require("igraph")||install.packages("igraph"))
try(require("ggraph")||install.packages("ggraph"))
try(require("stringr")||install.packages("stringr"))
try(require("tidytext")||install_github("juliasilge/tidytext"))
try(require("tidytext")||install.packages("tidytext"))

library("shiny")
library("tidytext")
library("tidyr")
library("dplyr")
library("ggplot2")
library("DT")
library("reshape2")
library("wordcloud")
library("plotly")
library("udpipe")
library("textrank")
library("lattice")
library("igraph")
library("ggraph")
library("ggplot2")
library("wordcloud")
library("stringr")
